### PR TITLE
Fix header check on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by ankane**
Currently, gems that rely on Rice fail to compile with Rice 4.6 on Ubuntu 22.04 due to a missing header.

Relevant console output

```text
checking for rice/rice.hpp in /home/runner/work/faiss-ruby/faiss-ruby/vendor/bundle/ruby/3.3.0/gems/rice-4.6.0/include... no
/home/runner/work/faiss-ruby/faiss-ruby/vendor/bundle/ruby/3.3.0/gems/rice-4.6.0/lib/mkmf-rice.rb:42:in `<top (required)>': Could not find rice/rice.hpp header (RuntimeError)
   from /opt/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
   from /opt/hostedtoolcache/Ruby/3.3.8/x64/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
   from ../../../../ext/faiss/extconf.rb:1:in `<main>'
rake aborted!
```

Relevant `mkmf.log` contents

```text
In file included from conftest.cc:3:
/home/runner/work/faiss-ruby/faiss-ruby/vendor/bundle/ruby/3.3.0/gems/rice-4.6.0/include/rice/rice.hpp: In function ‘void Rice::detail::for_each_tuple(Tuple_T&&, Function_T&&)’:
/home/runner/work/faiss-ruby/faiss-ruby/vendor/bundle/ruby/3.3.0/gems/rice-4.6.0/include/rice/rice.hpp:223:12: error: ‘apply’ is not a member of ‘std’
  223 |       std::apply([&callable](auto&& ...args)
      |            ^~~~~
In file included from conftest.cc:3:
/home/runner/work/faiss-ruby/faiss-ruby/vendor/bundle/ruby/3.3.0/gems/rice-4.6.0/include/rice/rice.hpp:79:1: note: ‘std::apply’ is defined in header ‘<tuple>’; did you forget to ‘#include <tuple>’?
   78 | #include <vector>
  +++ |+#include <tuple>
   79 | 
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <rice/rice.hpp>
/* end */
```

This PR adds `#include <tuple>` to files that use `std::apply`.

### CODE REVIEW

**Comment by cfis** [comment]
Thanks!

**Comment by ankane** [comment]
Thank you!

**Comment by cfis** [comment]
Did you update the rice header files? What error message are you getting?

**Comment by cfis** [comment]
And what is in mkmf.log?
