### ISSUE TITLE
Compilation fails with Ruby 1.9.3 with Falcon performance patches

### ISSUE THREAD

**Issue by adamtrilling** [ruby-rice/rice#47]
I was attempting to build rice using ruby 1.9.3 with the infamous Falcon performance patches (https://gist.github.com/4136373) and I get the following compiler error:

```
g++ -DHAVE_CONFIG_H -I.  -I/Users/adam/.rbenv/versions/1.9.3-p327-perf/include/ruby-1.9.1 -I/Users/adam/.rbenv/versions/1.9.3-p327-perf/include/ruby-1.9.1/x86_64-darwin10.8.0 -arch x86_64 -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Werror=pointer-arith -Werror=write-strings -Werror=declaration-after-statement -Werror=shorten-64-to-32 -Werror=implicit-function-declaration  -pipe -fno-common -arch x86_64 -I/Users/adam/.rbenv/versions/1.9.3-p327-perf/include/ruby-1.9.1 -I/Users/adam/.rbenv/versions/1.9.3-p327-perf/include/ruby-1.9.1/x86_64-darwin10.8.0 -c -o Struct.o Struct.cpp
In file included from detail/../to_from_ruby.hpp:5,
                 from detail/object_call.ipp:3,
                 from Object.ipp:7,
                 from Object.hpp:5,
                 from Builtin_Object.ipp:4,
                 from Builtin_Object.hpp:5,
                 from Array.hpp:4,
                 from Struct.hpp:4,
                 from Struct.cpp:1:
detail/../to_from_ruby.ipp: In function ‘typename Rice::detail::from_ruby_<T>::Retval_T from_ruby(Rice::Object) [with T = int]’:
detail/../to_from_ruby.ipp:42: warning: implicit conversion shortens 64-bit value into a 32-bit value
detail/../to_from_ruby.ipp: In function ‘typename Rice::detail::from_ruby_<T>::Retval_T from_ruby(Rice::Object) [with T = unsigned int]’:
detail/../to_from_ruby.ipp:104: warning: implicit conversion shortens 64-bit value into a 32-bit value
In file included from Hash.hpp:207,
                 from Struct.hpp:5,
                 from Struct.cpp:1:
Hash.ipp: In member function ‘Rice::Hash::Iterator<Hash_Ref_T, Value_T>& Rice::Hash::Iterator<Hash_Ref_T, Value_T>::operator++()’:
Hash.ipp:221: error: ‘struct st_table’ has no member named ‘bins’
Hash.ipp: In member function ‘Rice::Hash::Iterator<Rice::Hash&, Rice::Hash::Entry> Rice::Hash::begin()’:
Hash.ipp:289: error: ‘struct st_table’ has no member named ‘bins’
Hash.ipp: In member function ‘Rice::Hash::Iterator<const Rice::Hash&, const Rice::Hash::Entry> Rice::Hash::begin() const’:
Hash.ipp:296: error: ‘struct st_table’ has no member named ‘bins’
```

A tiny bit of digging into the config.log shows that it's falling back to the headers for the system ruby, which is 1.8.6 (I'm on Snow Leopard) when trying to find node.h.

It works fine with 1.9.3 unpatched, which is what I'll probably end up using in production for my app.  I'll dig further later, and I realize this is probably an edge case most people don't care about, but I'm putting this out here now just in case anyone who knows a lot more about rice than I do has any brilliant insights...
